# Site Settings
title: Hello, I'm Kasey!
url: https://kaseygreene.com
# enforce_ssl: kaseygreene.com
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
# permalink: /:title/
permalinke: /
kramdown:
  input: GFM
